<script setup>
import { ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { usePaged } from '../../utils/paged.js';
import Pagination from '../../components/Pagination.vue';
import { fmtDateTime } from '../../utils/format.js';

const route = useRoute(); const router = useRouter();
const f = ref({ action: route.query.action || '', actor: route.query.actor || '', target: route.query.target || '', from: route.query.from || '', to: route.query.to || '' });
const list = usePaged('/api/admin/audit', { key: 'entries', limit: 50, extraQuery: () => ({ ...f.value }) });
let t = null;
watch(f, () => { clearTimeout(t); t = setTimeout(() => router.replace({ query: Object.fromEntries(Object.entries(f.value).filter(([, v]) => v)) }), 300); }, { deep: true });
const LABELS = { 'user.register': 'Регистрация', 'user.login': 'Вход', 'user.login_failed': 'Неудачный вход', 'user.verify_email': 'Подтверждение e-mail', 'user.password_reset': 'Сброс пароля', 'user.password_change': 'Смена пароля', 'user.totp_enable': 'Включение 2FA', 'user.totp_disable': 'Отключение 2FA', 'user.token_create': 'Создан токен API', 'user.invite_accept': 'Принято приглашение', 'video.upload': 'Загрузка видео', 'video.update': 'Изменение видео', 'video.delete': 'Удаление видео', 'video.reprocess': 'Повторная обработка', 'comment.delete': 'Удаление комментария', 'comment.moderate': 'Модерация комментария', 'live.create': 'Создана трансляция', 'admin.user_update': 'Изменение пользователя', 'admin.user_active': 'Активация пользователя', 'admin.user_rejected': 'Отклонение заявки', 'admin.user_blocked': 'Блокировка пользователя', 'admin.user_delete': 'Удаление пользователя', 'admin.user_create': 'Создание пользователя', 'admin.user_reset_link': 'Ссылка сброса пароля', 'admin.invite': 'Приглашение', 'admin.domain_add': 'Добавлен домен', 'admin.domain_delete': 'Удалён домен', 'admin.video_approved': 'Видео одобрено', 'admin.video_rejected': 'Видео отклонено', 'admin.video_block': 'Видео заблокировано', 'admin.video_unblock': 'Видео разблокировано', 'admin.video_transfer': 'Передача видео', 'admin.comment_status': 'Статус комментария', 'admin.comment_delete': 'Удаление комментария', 'admin.report_resolved': 'Жалоба обработана', 'admin.report_dismissed': 'Жалоба отклонена', 'admin.settings': 'Изменение настроек', 'admin.announce': 'Рассылка объявления', 'admin.live_end': 'Завершение эфира', 'group.create': 'Создана группа', 'group.update': 'Изменена группа', 'group.delete': 'Удалена группа', 'group.members_add': 'Добавлены участники группы', 'group.members_remove': 'Исключён из группы', 'assignment.create': 'Назначено к просмотру', 'assignment.update': 'Изменено назначение', 'assignment.delete': 'Удалено назначение', 'assignment.remind': 'Напоминание о назначении', 'quiz.save': 'Сохранён тест', 'quiz.delete': 'Удалён тест', 'share.create': 'Создана защищённая ссылка', 'share.update': 'Изменена защищённая ссылка', 'share.delete': 'Удалена защищённая ссылка', 'video.replace': 'Замена файла видео', 'video.import_url': 'Импорт по ссылке', 'video.ai': 'Запрос ИИ-подсказок', 'video.attachment_add': 'Добавлен материал', 'video.attachment_delete': 'Удалён материал', 'video.rag_push': 'Выгрузка в RAG', 'admin.rag_push_all': 'Массовая выгрузка в RAG', 'admin.ai_describe_all': 'Массовое описание через ИИ', 'certificate.revoke': 'Отзыв сертификата', 'live.interact': 'Настройки интерактива эфира', 'video.edit': 'Монтаж видео', 'video.clip': 'Создан клип', 'video.ocr': 'Распознавание текста на экране', 'subtitles.translate': 'Перевод субтитров', 'video.scorm_export': 'Экспорт SCORM', 'webhook.create': 'Создан вебхук', 'webhook.update': 'Изменён вебхук', 'webhook.delete': 'Удалён вебхук', 'user.feed_token_reset': 'Сброс токена RSS' };
</script>

<template>
  <div>
    <div class="page-head"><div><h1>Журнал действий</h1><div class="sub">{{ list.total.value }} записей</div></div></div>
    <div class="row wrap mb-16"><input class="input" v-model="f.action" placeholder="Действие (напр. admin.)" style="max-width: 200px" /><input class="input" v-model="f.actor" placeholder="Кто (e-mail / канал)" style="max-width: 200px" /><input class="input" v-model="f.target" placeholder="ID объекта" style="max-width: 200px" /><input class="input" type="date" v-model="f.from" style="max-width: 160px" /><input class="input" type="date" v-model="f.to" style="max-width: 160px" /></div>
    <div class="table-wrap"><table class="table"><thead><tr><th>Время</th><th>Кто</th><th>Действие</th><th>Объект</th><th>Детали</th><th>IP</th></tr></thead><tbody>
      <tr v-for="e in list.items.value" :key="e.id"><td class="small nowrap">{{ fmtDateTime(e.createdAt) }}</td><td class="small"><router-link v-if="e.actor" :to="`/admin/users/${e.actor.id}`">{{ e.actor.name }}</router-link><span v-else class="muted">система</span></td><td><span class="badge" :class="e.action.startsWith('admin.') ? 'brand' : ''">{{ LABELS[e.action] || e.action }}</span></td><td class="small mono">{{ e.targetType }} {{ e.targetId ? e.targetId.slice(0, 12) : '' }}</td><td class="tiny mono" style="max-width: 360px; white-space: pre-wrap; word-break: break-all">{{ Object.keys(e.details || {}).length ? JSON.stringify(e.details) : '' }}</td><td class="small mono">{{ e.ip }}</td></tr>
      <tr v-if="!list.items.value.length"><td colspan="6" class="muted">Записей нет</td></tr>
    </tbody></table></div>
    <Pagination :page="list.page.value" :total="list.total.value" :limit="50" @change="list.setPage" />
  </div>
</template>
